### ISSUE TITLE
bug repot in player page

### ISSUE THREAD

**Issue by senecas** [WessTorn/kreedz-web-stats#2]
Thank you~ for make this kz-stats ( cuz I have plan to use Theggv's Kreedz   :)
I not sure this project finishing or wip. but found bugs here. so report

1.  
```
2023/05/11 09:24:27 http: panic serving *.*.*.*:57406: sql: expected 3 destination arguments in Scan, not 4
goroutine 130 [running]:
net/http.(*conn).serve.func1()
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:1854 +0xbf
panic({0x80db80, 0xc00043f160})
        /home/wesstorn/go/go1.20.1/src/runtime/panic.go:890 +0x263
main.GetStatusPlayer.func1({0x9215a0?, 0xc00013a540}, 0xc000363a10?)
        /home/wesstorn/go_wess/kreedz-web-stats/backend/player.go:41 +0xaa5
net/http.HandlerFunc.ServeHTTP(0xc0000d9900?, {0x9215a0?, 0xc00013a540?}, 0xba15a0?)
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000180, {0x9215a0, 0xc00013a540}, 0xc0000d9800)
        /home/wesstorn/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.(*ServeMux).ServeHTTP(0x0?, {0x9215a0, 0xc00013a540}, 0xc0000d9800)
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0xc0003840c0?}, {0x9215a0, 0xc00013a540}, 0xc0000d9800)
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000382090, {0x921918, 0xc000178450})
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:3089 +0x5ed
```
2. 
```
2023/05/11 09:52:38 http: panic serving *.*.*.*:1949: template: player.gohtml:14:39: executing "player" at <.Players.Avatar>: can't evaluate field Avatar in type main.Player
goroutine 84 [running]:
net/http.(*conn).serve.func1()
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:1854 +0xbf
panic({0x847000, 0xc000512a80})
        /home/wesstorn/go/go1.20.1/src/runtime/panic.go:890 +0x263
main.GetStatusPlayer.func1({0x9215a0?, 0xc0000ba460}, 0xc0001d2cc0?)
        /home/wesstorn/go_wess/kreedz-web-stats/backend/player.go:109 +0xa0b
net/http.HandlerFunc.ServeHTTP(0xc000511a00?, {0x9215a0?, 0xc0000ba460?}, 0xba15a0?)
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00011a0c0, {0x9215a0, 0xc0000ba460}, 0xc000511900)
        /home/wesstorn/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.(*ServeMux).ServeHTTP(0x0?, {0x9215a0, 0xc0000ba460}, 0xc000511900)
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0xc000292d80?}, {0x9215a0, 0xc0000ba460}, 0xc000511900)
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0003062d0, {0x921918, 0xc00013a000})
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /home/wesstorn/go/go1.20.1/src/net/http/server.go:3089 +0x5ed
```

**Comment by WessTorn** [comment]
I'll be back to developing this project soon
I'll rework it and fix it
